on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - run : sudo apt-get --assume-yes install asciidoctor 
    - run : make all
    - name: My first step
      if: ${{ github.event_name == 'pull_request' }}
      run: linkchecker --check-extern ./dist/index.html
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      uses : netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
  
  