name: Netlify
on: [push]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - run : sudo apt-get --assume-yes install asciidoctor 
    - run : make all
    - name: Tests
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
      run: linkchecker --check-extern ./index.html
    - name: Publish
      if: ${{github.event_name == 'push'}}
      uses : netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}