name: Netlify
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - run : sudo apt-get -y install asciidoctor 
    - run : make all
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Publish
      uses : netlify/actions/cli@master
      with:
        args: deploy --dir=dist --functions=functions
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKKEN}}
    - run : netlify deploy --prod --dir=./dist/